project:
  type: book

book:
  title: "Bioinformatics Protocols"
  author: "Viriya Keo"
  date: "06/20/2024"
  chapters:
    - index.qmd
    - pipelines.qmd
    - bulk.qmd
    - functional.qmd
    - 3D.qmd
    - single-cell.qmd
    - resources.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-copy: true
    code-tools: true
  pdf:
    documentclass: scrreprt

editor: visual
execute:
  freeze: auto

