# Preface {.unnumbered}

This is a summary of commonly used pipelines and data analysis protocols used in the Yu Lab. Furthermore, it includes many the tips and tricks I've learned and kept track of. I consider this a mini-cookbook of sorts.

This book is not an exhaustive list of everything we do in the lab. For example, I do not have any experience with DiMeLo-Seq data analysis. I also do not consider this the best practices or the only possible way of doing things, but I've tried my best to pick the best/easiest methods. However, the code for book is published on GitHub and any lab member can contribute to it in the future and add more sections or change approaches.

I've tried to follow the typical life cycle of NGS data analysis in organizing the book. We start with basic QC and processing pipelines. The chapters following are method specific analysis. At the end, I have programming tips as well as general resources that have helped me immensely in learning everything in this book. More specific resources are provided where relevant.

I try to keep this short and not include all of the background for certain decisions made. Some of the code included may seem very trivial but I would've wished I had the handy snippets when I started out. I also assume you already know some basics.

This book was written in Quarto. To learn more about Quarto books visit <https://quarto.org/docs/books>.
